README.md: guessinggame.sh
	@echo "Generating README.md..."
	@echo "# Guessing Game" > README.md
	@echo "Date and time of creation: $(shell date)" >> README.md
	@echo "Number of lines in guessinggame.sh: $(shell wc -l < guessinggame.sh)" >> README.md
	@echo "This README was generated by the Makefile." >> README.md
	@echo "README.md generated successfully."

